version: '3'

services:
    app:
        build: docker/app
        volumes:
            - ./:/var/www/html
        ports:
            - 80:80
            - 9229:9229
        depends_on:
            - db
        environment:
            PATH: $PATH:/var/www/html/node_modules/.bin/

    db:
        image: mysql:5.6
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dev
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
        volumes:
            - vol_db:/var/lib/mysql
volumes:
    vol_db: {}
